### PR TITLE
Inject GORM Data Services only after all other core datastore beans have been injected

### LINKED ISSUE #185: Application freezes when injecting DataSource bean into GORM data service
### Task List

- [x] Steps to reproduce provided
- [ ] Stacktrace (if present) provided
- [x] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. Create a factory bean for the purpose of creating a`groovy.sql.Sql` bean
2. Create a GORM data service that has said bean injected
3. Run anything that causes the data service bean to be instantiated

### Expected Behaviour

A DataSource bean is injected into the Sql factory method

### Actual Behaviour

The application freezes when retrieving the bean from the ApplicationContext 

### Environment Information

- **Operating System**: MacOS 10.15.7
- **Micronaut Version:** 2.3.1
- **JDK Version:** 11

### Example Application

- https://github.com/jamesdh/demo/tree/micronaut_groovy_185

### PR DESCRIPTION
**Pull request by jamesdh**
Fixes #185. 

Fixes a "chicken or the egg" problem with regards to HibernateDatastoreFactory generated beans and any GORM Data Services that might be dependent on said beans.

### CODE REVIEW

File: hibernate-gorm/src/main/groovy/io/micronaut/configuration/hibernate/gorm/HibernateDatastoreFactory.groovy [hunk 1]
```diff
@@ -63,33 +62,20 @@ class HibernateDatastoreFactory {
...
-    @Singleton
-    void setupServices(HibernateDatastore hibernateDatastore, SessionFactory sessionFactory, DataSource dataSource, PlatformTransactionManager platformTransactionManager) {
-        for (o in hibernateDatastore.getServices()) {
+        SessionFactory sessionFactory = datastore.sessionFactory
+        DataSource dataSource = ((HibernateConnectionSource) datastore.getConnectionSources().defaultConnectionSource).getDataSource()
+        PlatformTransactionManager platformTransactionManager = datastore.getTransactionManager()
+        applicationContext.registerSingleton(SessionFactory, sessionFactory)
+        applicationContext.registerSingleton(DataSource, dataSource)
+        applicationContext.registerSingleton(PlatformTransactionManager, platformTransactionManager, Qualifiers.byName("hibernate"))
+        applicationContext.registerSingleton(PlatformTransactionManager, platformTransactionManager, Qualifiers.byStereotype(Primary))
```
Comment (jamesdh) [inline hibernate-gorm/src/main/groovy/io/micronaut/configuration/hibernate/gorm/HibernateDatastoreFactory.groovy:71]: I tried using a CompositeQualifier for this but the bean lookup in the test would fail no matter how I tried to do it. Registering the same bean twice with different Qualifier's seems to work fine though.

File: hibernate-gorm/src/main/groovy/io/micronaut/configuration/hibernate/gorm/HibernateDatastoreFactory.groovy [hunk 2]
```diff
@@ -63,30 +63,27 @@ class HibernateDatastoreFactory {
...
         }
-        for (o in datastore.getServices()) {
-            applicationContext.inject(o)
+        for(services in gormServices) {
+            for (o in services) {
+                applicationContext.registerSingleton(o, false)
+            }
+            for (o in services) {
+                applicationContext.inject(o)
+            }
```
Comment (jamesdh) [inline hibernate-gorm/src/main/groovy/io/micronaut/configuration/hibernate/gorm/HibernateDatastoreFactory.groovy:83]: Divides the services by those that simply implement the Service interface (e.g. those already provided by GORM) and those which have it weaved in via the @Service annotation (those provided by the project), and then registers them in that order.

File: hibernate-gorm/src/main/groovy/io/micronaut/configuration/hibernate/gorm/HibernateDatastoreFactory.groovy [hunk 3]
```diff
@@ -86,4 +88,22 @@ class HibernateDatastoreFactory {
...
+    }
+
+    @Primary
+    @Named("hibernate")
+    @Singleton
+    PlatformTransactionManager transactionManager(HibernateDatastore hibernateDatastore) {
+        hibernateDatastore.getTransactionManager()
+    }
+
+
```
Comment (jamesdh) [inline hibernate-gorm/src/main/groovy/io/micronaut/configuration/hibernate/gorm/HibernateDatastoreFactory.groovy]: Had to re-add these Singleton bean methods because I was experiencing transactional issues in actual usage otherwise. Guessing something is done at compile-time and simply registering/injecting the beans via the ApplicationContext is insufficient.

**Comment by graemerocher** [comment]
Thanks for the contribution!
